### ISSUE TITLE
The open source license is missing

### ISSUE THREAD

**Issue by ShannonZ** [mribri999/MRSignalsSeqs#11]
FYI

**Comment by mribri999** [comment]
Our work is mostly in imaging, specifically MRI.  The center of the image and the center of the k-space are both zero.  The FFTs are defined assuming 0 is at the edge of an array.

So when we view images or k-space we usually want the 0-point to be in the center, so we shift the array before and after the FFT.  In your example below, your k-space would have a large linear phase.

**Comment by ShannonZ** [comment]
I‘ve found the answer. In MRI, the spatial coordinate range are [-x,/2 x/2]. But the matlab FFT use [0, x].
